services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: glassweb_backend
    ports:
      - "8000:8000"
    environment:
      - GLASSWEB_NAV_TIMEOUT_MS=45000
      - GLASSWEB_POST_LOAD_WAIT_MS=3000
    mem_limit: 1g
    volumes:
      - ./backend:/app
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --loop asyncio --reload

  frontend:
    image: nginx:alpine
    container_name: glassweb_frontend
    ports:
      - "8080:80"
    volumes:
      - ./frontend:/usr/share/nginx/html:ro